version: '2'
services:
  nginx-status-exporter:
    image: simanchou/nginx_status_exporter:v0.1.0
    volumes:
      - ./conf.yml:/opt/app/conf.yml
      - ./nginx_status_exporter.py:/opt/app/nginx_status_exporter.py
    network_mode: "host"
    restart: always
